apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-helper-cron
spec:
  schedule: {{ .Values.cronSchedule }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount }}
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          - name: kubectl
            imagePullPolicy: Always
            image: proscia/aws_ecr_helper:{{ .Values.imageVersion }}
            command:
              - "/run.sh"
            env:
              - name: AWS_ACCOUNT
                value: {{ .Values.awsAccount }}
              - name: AWS_REGION
                value: {{ .Values.awsRegion }}
              - name: NAMESPACES
                value: {{ .Values.namespace }}
              - name: AWS_ACCESS_KEY_ID
                value: {{ .Values.awsAccessKeyId }}
              - name: AWS_SECRET_ACCESS_KEY
                value: {{ .Values.awsSecretAccessKey }}